x-health: &default-healthcheck
  interval: 10s
  timeout: 30s
  retries: 2

services:
  db:
    image: postgres:16-alpine
    container_name: fawapp-db
    volumes:
      - fawapp_postgresdb:/var/lib/postgresql/data
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    ports:
      - "5432:5432"
    env_file:
      - ./db/.env
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: PGPASSWORD=${DB_PASSWORD} psql -h localhost -p 5432 -U ${DB_USER} -d ${DB_NAME} -c "select 1;" 2>&1 > /dev/null || exit 1
      <<: *default-healthcheck
    restart: always
  app:
    build: .
    container_name: fawapp-app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 --log-config app/log_config.json
    depends_on:
      - db
    expose:
      - "8000"
    healthcheck:
      test: [ "CMD", "python", "-c", "import http.client; conn = http.client.HTTPConnection('localhost', 8000); conn.request('GET', '/api/health-check'); response = conn.getresponse(); exit(1) if response.status != 200 else exit(0)" ]
      <<: *default-healthcheck
    volumes:
      - .:/work
    restart: always
  nginx:
    image: nginx:alpine
    container_name: fawapp-nginx
    healthcheck:
      test: curl http://localhost/nginx || exit 1
      <<: *default-healthcheck
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx/data/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/data/conf.d:/etc/nginx/conf.d/:ro
    restart: always

volumes:
  fawapp_postgresdb:
